### ISSUE TITLE
Switch away from yarn

### ISSUE THREAD

**Issue by tmcw** [placemark/placemark#32]
This uses `yarn 1.x` to install dependencies, which is pretty old and nobody uses it anymore. We should switch to `npm` or `pnpm`. Maybe pnpm.

The main issue to solve is that there's a lockfile keeping deps in place and once we upgrade to newly-resolved deps, we get:

```
 ⨯ Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/tmcw/p/placemark-oss/node_modules/.pnpm/@mapbox+tiny-sdf@2.0.6/node_modules/@mapbox/tiny-sdf/index.js from /Users/tmcw/p/placemark-oss/node_modules/.pnpm/@deck.gl+layers@8.9.34_@deck.gl+core@8.9.34_@loaders.gl+core@3.4.14_@luma.gl+core@8.5.21/node_modules/@deck.gl/layers/dist/es5/text-layer/font-atlas-manager.js not supported.
Instead change the require of index.js in /Users/tmcw/p/placemark-oss/node_modules/.pnpm/@deck.gl+layers@8.9.34_@deck.gl+core@8.9.34_@loaders.gl+core@3.4.14_@luma.gl+core@8.5.21/node_modules/@deck.gl/layers/dist/es5/text-layer/font-atlas-manager.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (/Users/tmcw/p/placemark-oss/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at Object.<anonymous> (/Users/tmcw/p/placemark-oss/node_modules/.pnpm/@deck.gl+layers@8.9.34_@deck.gl+core@8.9.34_@loaders.gl+core@3.4.14_@luma.gl+core@8.5.21/node_modules/@deck.gl/layers/dist/es5/text-layer/font-atlas-manager.js:17:39)
    at mod.require (/Users/tmcw/p/placemark-oss/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at Object.<anonymous> (/Users/tmcw/p/placemark-oss/node_modules/.pnpm/@deck.gl+layers@8.9.34_@deck.gl+core@8.9.34_@loaders.gl+core@3.4.14_@luma.gl+core@8.5.21/node_modules/@deck.gl/layers/dist/es5/text-layer/text-layer.js:32:49) {
  code: 'ERR_REQUIRE_ESM',
  page: '/map/zJ7HAtjokRyftNNmNEHiX'
}
```

This is [upstream in deckgl/layers #7735](https://github.com/visgl/deck.gl/issues/7735).

**Comment by stevage** [comment]
With NPM I get:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: placemark@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.3 || ^17.0.0" from react-virtual@2.10.4
npm ERR! node_modules/react-virtual
npm ERR!   react-virtual@"^2.10.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Running `npm install --force` seems to work.

With `bun install`, it seems to install ok with some warnings:

```
bun install v1.0.25 (a8ff7be6)
warn: incorrect peer dependency "react@18.2.0"

warn: incorrect peer dependency "react@18.2.0"

...(x~10)
```

By "seems to work" I mean it is able to run `dev` ok and I am able to get as far as attempting to log in. (Haven't set up a Postgres yet to test any further...)

**Comment by tmcw** [comment]
I think, unfortunately, the scheme of priorities here is that **running a free version of /play** is priority 1, but in order to do that, I either need to do a dirty fork of the placemark source, or run a monorepo, and in order to run a monorepo, I need to switch version managers, which means I need to deal with this issue. Pinning the transitive dep might be a solution. I wish that there was a solution upstream from Deck or Mapbox.
